name: namester
description: A simple command-line application.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  # shelf: '^1.1.4'
  # shelf_router: ^1.0.0
  shelf_plus: ^0.0.2
  json_serializable: ^4.1.3

dev_dependencies:
  http: ^0.13.3
  pedantic: ^1.9.0
  build_runner: ^2.0.4
